apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: appointments-cluster
  region: us-east-1

vpc:
  id: vpc-0072131fd92d34dca
  subnets:
    private:
      us-east-1a:
        id: subnet-0df10f0ec0f044fa0
      us-east-1b:
        id: subnet-09750ae810db4c968

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: true
