version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - yum install -y mysql
      - pip3 install -r requirements-dev.txt
      - pip3 install boto3 django-iam-dbauth pymysql cryptography

  build:
    commands:
      - echo "Creating database if it doesn't exist..."
      - mysql -h $DATABASE_HOST -u $DATABASE_USER -p$DATABASE_PASSWORD -e "CREATE DATABASE IF NOT EXISTS Appointments;"
      - echo "Running Django migrations..."
      - python manage.py migrate
      - echo "Listing tables..."
      - mysql -h $DATABASE_HOST -u $DATABASE_USER -p$DATABASE_PASSWORD Appointments -e "SHOW TABLES;"

env:
  variables:
    DATABASE_HOST: "webhost-mydb-gtomgss6desb.c6raww6uqmxp.us-east-1.rds.amazonaws.com"
    DATABASE_USER: "dbadmin"
    DATABASE_DB_NAME: "Appointments"
  parameter-store:
    DATABASE_PASSWORD: "/rds/dbadmin/password"
