"""
Django settings for hairdresser_django project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-pzza694=ew*esxkv0ebe$ou@awr$a^mh-9u2p42)&%4$2izb1z')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Business configuration
BUSINESS_TYPE = os.environ.get('BUSINESS_TYPE', 'hairdresser')  # or 'nail'
BUSINESS_NAME = os.environ.get('BUSINESS_NAME', 'Hair Salon')
PROVIDER_TITLE = os.environ.get('PROVIDER_TITLE', 'Hairdresser')  # or 'Nail Technician'
PROVIDER_TITLE_PLURAL = os.environ.get('PROVIDER_TITLE_PLURAL', 'Hairdressers')  # or 'Nail Technicians'

# Demo mode configuration - allows public access to admin
DEMO_MODE = os.environ.get('DEMO_MODE', 'True') == 'True'

# Color scheme configuration
PRIMARY_COLOR = os.environ.get('PRIMARY_COLOR', '#f5a3b8')  # Default: pink
SECONDARY_COLOR = os.environ.get('SECONDARY_COLOR', '#d4af37')  # Default: rose gold
ACCENT_COLOR = os.environ.get('ACCENT_COLOR', '#fce4ec')  # Default: soft blush
BACKGROUND_COLOR = os.environ.get('BACKGROUND_COLOR', '#f0e6d8')  # Default: warm beige

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

CSRF_TRUSTED_ORIGINS = [
    'https://*.amazonaws.com',
    'https://*.elb.amazonaws.com',
    'https://*.awsapprunner.com',
    'http://127.0.0.1',
    'http://localhost',
    'https://*.cloudfront.net',
    'http://luxe-hair-studio-alb-738301618.us-east-1.elb.amazonaws.com',
    'https://luxe-hair-studio-alb-738301618.us-east-1.elb.amazonaws.com'
]

# Additional CSRF settings for load balancer
CSRF_COOKIE_SECURE = False  # Set to False for HTTP ALB
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'

# CSRF settings for production deployment
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True


# Application definition

INSTALLED_APPS = [
    'appointments.apps.AppointmentsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'appointments.auth_backends.PublicAdminMiddleware',  # Auto-login for demo mode
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CSRF settings for production
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False

ROOT_URLCONF = 'hairdresser_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'appointments.context_processors.business_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'hairdresser_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if (
    "DATABASE_HOST" in os.environ
    and "DATABASE_USER" in os.environ
    and "DATABASE_DB_NAME" in os.environ
):
    import pymysql
    pymysql.install_as_MySQLdb()
    
    # Use IAM auth if no password provided, otherwise use password
    if "DATABASE_PASSWORD" in os.environ:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "HOST": os.environ["DATABASE_HOST"],
                "USER": os.environ["DATABASE_USER"],
                "PASSWORD": os.environ["DATABASE_PASSWORD"],
                "NAME": os.environ["DATABASE_DB_NAME"],
                "OPTIONS": {
                    "sql_mode": "traditional",
                    "ssl": {"ssl_mode": "REQUIRED"},
                },
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django_iam_dbauth.aws.mysql",
                "HOST": os.environ["DATABASE_HOST"],
                "USER": os.environ["DATABASE_USER"],
                "NAME": os.environ["DATABASE_DB_NAME"],
                "OPTIONS": {
                    "sql_mode": "traditional",
                    "use_iam_auth": True,
                    "ssl": {"ssl_mode": "REQUIRED"},
                },
            }
        }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Allauth Configuration
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'appointments.auth_backends.DemoAdminBackend',  # Demo mode authentication
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Simple email-based authentication
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Simplified for demo

# Demo email backend (prints to console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

TEST_RUNNER = 'xmlrunner.extra.djangotestrunner.XMLTestRunner'
TEST_OUTPUT_FILE_NAME = 'unittests.xml'
