# Generated by Django 5.0.14 on 2025-12-09 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_populate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hairdresser',
            options={'verbose_name': 'Service Provider', 'verbose_name_plural': 'Service Providers'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hairdresser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.hairdresser', verbose_name='Provider'),
        ),
    ]
