# Generated by Django 5.0.14 on 2025-12-10 00:18

from django.db import migrations


def populate_services(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    services = [
        {
            'service_name': 'Weave Install With Closure',
            'description': '$75 Deposit Required. $310 & UP! Includes Shampoo, conditioning, blow-dry, braid down, sew-in, flatiron/rollerset style. Pricing may increase based on density and length of hair.',
            'price': 310.00,
            'duration': 150  # 2 hr 30 min
        },
        {
            'service_name': 'Wrap and Style (relaxed short hair)',
            'description': 'Wrap and style for relaxed short hair. Trims are an extra fee of $35.00. Partially relaxed hair is extra per stylist discretion. Pincurls are $10 extra.',
            'price': 70.00,
            'duration': 60  # 1 hr
        },
        {
            'service_name': 'Up-Do',
            'description': 'Up-do is an extra service to what the client is already getting. Pricing might increase based on density/length of hair and amount of product required for service. Extra Hair is an additional fee.',
            'price': 40.00,
            'duration': 45  # 45 min
        },
        {
            'service_name': 'Two Strand Twist - Full Head (own hair)',
            'description': '$150 & UP. Shampoo is included. Pricing might increase based on density/length of hair and amount of product required for service.',
            'price': 150.00,
            'duration': 45  # 45 min
        },
        {
            'service_name': 'Shampoo Only',
            'description': 'Pricing might increase based on density/length of hair and amount of product required for service. Shampoo and Conditioner $35. Deep Conditioner $50. Extended Head Massage also available.',
            'price': 25.00,
            'duration': 20  # 20 min
        },
        {
            'service_name': 'Braids - Box Braids',
            'description': '$75 Deposit Required. $245 and UP. Hair not included. Includes shampoo, conditioning, blow-dry, and braids. Pricing depends on the length, size, and density of the hair.',
            'price': 245.00,
            'duration': 240  # 4 hr
        },
        {
            'service_name': 'Cornrow - Crown own hair',
            'description': 'Cornrow braiding using your own hair.',
            'price': 75.00,
            'duration': 30  # 30 min
        },
        {
            'service_name': 'Color - Permanent Full Head',
            'description': 'Full head color, extra tube - add. price.',
            'price': 90.00,
            'duration': 90  # 1.5 hr
        },
        {
            'service_name': 'Color - Permanent Root Touchup',
            'description': '1 inch out starts at $65 and up.',
            'price': 65.00,
            'duration': 60  # 1 hr
        },
        {
            'service_name': 'Blow-Dry Only',
            'description': 'Pricing might increase based on density/length of hair and amount of product required for service.',
            'price': 25.00,
            'duration': 15  # 15 min
        },
        {
            'service_name': 'Protein (Aphogee)',
            'description': 'Includes a deep conditioner. Pricing might increase based on density/length of hair. Short hair $45, Long $60+.',
            'price': 45.00,
            'duration': 45  # 45 min
        },
        {
            'service_name': 'Seabreeze Scalp Detox',
            'description': 'Pricing might increase based on density/length of hair and amount of product required for service.',
            'price': 20.00,
            'duration': 20  # 20 min
        },
    ]
    
    for service_data in services:
        Service.objects.create(**service_data)


def reverse_populate(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    Service.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_hairdresser_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_services, reverse_populate),
    ]
