# Generated by Django 5.0.14 on 2025-12-10 00:30

from django.db import migrations


def update_descriptions(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Update Weave Install With Closure
    weave = Service.objects.filter(service_name='Weave Install With Closure').first()
    if weave:
        weave.description = '$75 Deposit Required. $310 & UP! Includes Shampoo, conditioning, blow-dry, braid down, sew-in, flatiron/rollerset style. Pricing may increase based on density and length of hair.'
        weave.save()
    
    # Update Wrap and Style
    wrap = Service.objects.filter(service_name='Wrap and Style (relaxed short hair)').first()
    if wrap:
        wrap.description = 'Wrap and style for relaxed short hair. Trim is extra fee.'
        wrap.save()


def reverse_update(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Revert Weave Install With Closure
    weave = Service.objects.filter(service_name='Weave Install With Closure').first()
    if weave:
        weave.description = '$75 Deposit Required. $310 & UP! HAIR NOT INCLUDED. Includes Shampoo, conditioning, blow-dry, braid down, sew-in, flatiron/rollerset style. Hair is available for purchase. Pricing may increase based on density and length of hair.'
        weave.save()
    
    # Revert Wrap and Style
    wrap = Service.objects.filter(service_name='Wrap and Style (relaxed short hair)').first()
    if wrap:
        wrap.description = 'Wrap and style for relaxed short hair.'
        wrap.save()


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_populate_services'),
    ]

    operations = [
        migrations.RunPython(update_descriptions, reverse_update),
    ]
