# Generated by Django 5.0.14 on 2025-12-10 00:35

from django.db import migrations


def update_shampoo_description(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Update Shampoo Only service
    shampoo = Service.objects.filter(service_name='Shampoo Only').first()
    if shampoo:
        shampoo.description = 'Pricing might increase based on density/length of hair and amount of product required for service. Shampoo and Conditioner $35. Deep Conditioner $50.'
        shampoo.save()


def reverse_shampoo_update(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Revert Shampoo Only service
    shampoo = Service.objects.filter(service_name='Shampoo Only').first()
    if shampoo:
        shampoo.description = 'Pricing might increase based on density/length of hair and amount of product required for service.'
        shampoo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_update_service_descriptions'),
    ]

    operations = [
        migrations.RunPython(update_shampoo_description, reverse_shampoo_update),
    ]