# Generated by Django 5.0.14 on 2025-12-10 00:40

from django.db import migrations


def update_service_descriptions(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Update Weave Install With Closure - remove deposit and pricing text
    weave = Service.objects.filter(service_name='Weave Install With Closure').first()
    if weave:
        weave.description = 'Includes Shampoo, conditioning, blow-dry, braid down, sew-in, flatiron/rollerset style. Pricing may increase based on density and length of hair.'
        weave.save()
    
    # Update Wrap and Style - add partially relaxed hair note
    wrap = Service.objects.filter(service_name='Wrap and Style (relaxed short hair)').first()
    if wrap:
        wrap.description = 'Wrap and style for relaxed short hair. Trim is extra fee. Partially relaxed hair is extra.'
        wrap.save()
    
    # Update Protein (Aphogee) - remove medium length pricing
    protein = Service.objects.filter(service_name='Protein (Aphogee)').first()
    if protein:
        protein.description = 'Includes a deep conditioner. Pricing might increase based on density/length of hair. Short hair $45, Long $60+.'
        protein.save()


def reverse_service_updates(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Revert Weave Install With Closure
    weave = Service.objects.filter(service_name='Weave Install With Closure').first()
    if weave:
        weave.description = '$75 Deposit Required. $310 & UP! Includes Shampoo, conditioning, blow-dry, braid down, sew-in, flatiron/rollerset style. Pricing may increase based on density and length of hair.'
        weave.save()
    
    # Revert Wrap and Style
    wrap = Service.objects.filter(service_name='Wrap and Style (relaxed short hair)').first()
    if wrap:
        wrap.description = 'Wrap and style for relaxed short hair. Trim is extra fee.'
        wrap.save()
    
    # Revert Protein (Aphogee)
    protein = Service.objects.filter(service_name='Protein (Aphogee)').first()
    if protein:
        protein.description = 'Includes a deep conditioner. Pricing might increase based on density/length of hair. Short hair $45, Medium length hair $50, Long $60+.'
        protein.save()


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_update_shampoo_service'),
    ]

    operations = [
        migrations.RunPython(update_service_descriptions, reverse_service_updates),
    ]