# Generated by Django 5.0.14 on 2025-12-10 01:00

from django.db import migrations


def update_wrap_style_description(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Update Wrap and Style service with detailed description
    wrap = Service.objects.filter(service_name='Wrap and Style (relaxed short hair)').first()
    if wrap:
        wrap.description = 'Wrap and style for relaxed short hair. Trims are an extra fee of $35.00. Partially relaxed hair is extra per stylist discretion. Pincurls are $10 extra.'
        wrap.save()


def reverse_wrap_style_update(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Revert Wrap and Style service
    wrap = Service.objects.filter(service_name='Wrap and Style (relaxed short hair)').first()
    if wrap:
        wrap.description = 'Wrap and style for relaxed short hair. Trim is extra fee. Partially relaxed hair is extra.'
        wrap.save()


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_update_multiple_services'),
    ]

    operations = [
        migrations.RunPython(update_wrap_style_description, reverse_wrap_style_update),
    ]