# Generated by Django 5.0.14 on 2025-12-10 01:05

from django.db import migrations


def update_service_descriptions(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Update Color - Permanent Full Head
    color = Service.objects.filter(service_name='Color - Permanent Full Head').first()
    if color:
        color.description = 'Full head color, extra tube - add. price.'
        color.save()
    
    # Update Shampoo Only
    shampoo = Service.objects.filter(service_name='Shampoo Only').first()
    if shampoo:
        shampoo.description = 'Pricing might increase based on density/length of hair and amount of product required for service. Shampoo and Conditioner $35. Deep Conditioner $50. Extended Head Massage also available.'
        shampoo.save()


def reverse_service_updates(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Revert Color - Permanent Full Head
    color = Service.objects.filter(service_name='Color - Permanent Full Head').first()
    if color:
        color.description = 'Full head color, extra tube - additional price.'
        color.save()
    
    # Revert Shampoo Only
    shampoo = Service.objects.filter(service_name='Shampoo Only').first()
    if shampoo:
        shampoo.description = 'Pricing might increase based on density/length of hair and amount of product required for service. Shampoo and Conditioner $35. Deep Conditioner $50.'
        shampoo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_update_wrap_style_detailed'),
    ]

    operations = [
        migrations.RunPython(update_service_descriptions, reverse_service_updates),
    ]