# Generated by Django 5.0.14 on 2025-12-10 01:10

from django.db import migrations


def update_updo_description(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Update Up-Do service
    updo = Service.objects.filter(service_name='Up-Do').first()
    if updo:
        updo.description = 'Up-do is an extra service to what the client is already getting. Pricing might increase based on density/length of hair and amount of product required for service. Extra Hair is an additional fee.'
        updo.save()


def reverse_updo_update(apps, schema_editor):
    Service = apps.get_model('appointments', 'Service')
    
    # Revert Up-Do service
    updo = Service.objects.filter(service_name='Up-Do').first()
    if updo:
        updo.description = 'Up-do is an extra service to what the client is already getting. Pricing might increase based on density/length of hair and amount of product required for service.'
        updo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_update_color_and_shampoo_services'),
    ]

    operations = [
        migrations.RunPython(update_updo_description, reverse_updo_update),
    ]