# Generated by Django 5.0.14 on 2025-12-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_update_updo_service'),
    ]

    operations = [
    ]
